from pathlib import Path
import ast,subprocess,re,json
root=Path('/private/tmp/kodezart-v03-m1-session-policy-extraction')
donor='1f4296c8c36a7498625d2478f8ec7ae6ec187923'
manifest=[]
def source(p):return subprocess.check_output(['git','show',f'{donor}:{p}'],cwd=root,text=True)
def put(p,s,reason):
 (root/p).parent.mkdir(parents=True,exist_ok=True);(root/p).write_text(s);manifest.append({'path':p,'donor':donor,'cut':reason})
def edit(p,changes,reason):
 s=(root/p).read_text()
 for a,b in changes:
  assert a in s,(p,a);s=s.replace(a,b)
 put(p,s,reason)
def node(p,name):
 s=source(p);n=next(n for n in ast.parse(s).body if getattr(n,'name',None)==name or isinstance(n,ast.TypeAlias) and n.name.id==name)
 return '\n'.join(s.splitlines()[n.lineno-1:n.end_lineno])
p='src/kodezart/types/domain/session.py';s=(root/p).read_text();insert='\n\n'.join(node(p,n) for n in ['PermissionMode','ToolPreset','AllowedTools']);put(p,s.replace('class SessionType(StrEnum):',insert+'\n\n\nclass SessionType(StrEnum):'),'Exact PermissionMode/ToolPreset/AllowedTools nodes only; KnowledgeGrant and SessionType unchanged')
p='src/kodezart/adapters/_permission_modes.py';put(p,source(p),'Exact entire SDK permission translation module')
p='src/kodezart/adapters/_agents_mapping.py';put(p,source(p),'Exact entire module; only AllowedTools import and SDK tool preset map/expansion differ from baseline')
p='src/kodezart/core/constants.py';s=(root/p).read_text();s=s.replace('EVAL_PERMISSION_MODE = "plan"','from kodezart.types.domain.session import PermissionMode\n\nEVAL_PERMISSION_MODE = PermissionMode.PLAN').replace('UNATTENDED_PERMISSION_MODE = "bypassPermissions"','UNATTENDED_PERMISSION_MODE = PermissionMode.UNATTENDED');s='\n'.join(l for l in s.splitlines() if not l.startswith(('EVAL_TOOLS:', 'EVAL_TOOLS_WITH_AGENT:', 'TICKET_TOOLS:')))+'\n';put(p,s,'Exact permission constants/removal of migrated tool lists; ARTIFACT_DIR remains later consumer-owned')
# Existing signature closure only.
paths=['adapters/claude_agent_executor.py','adapters/claude_client_executor.py','chains/ralph_loop.py','chains/ralph_workflow.py','composition/engine.py','core/protocols.py','services/agent_service.py','services/prompt_pass.py']
for rel in paths:
 p='src/kodezart/'+rel;s=(root/p).read_text();assert 'permission_mode: str' in s,p;s=s.replace('permission_mode: str','permission_mode: PermissionMode').replace('allowed_tools: list[str]','allowed_tools: AllowedTools');s='from kodezart.types.domain.session import AllowedTools, PermissionMode\n'+s if not s.startswith('"""') else s
 # add before first kodezart import (after module docstring)
 if 'from kodezart.types.domain.session import AllowedTools, PermissionMode' not in s:
  i=s.index('from kodezart.');s=s[:i]+'from kodezart.types.domain.session import AllowedTools, PermissionMode\n'+s[i:]
 if rel.startswith('adapters/claude_'):
  s=s.replace('    map_agents,','    map_agents,\n    map_allowed_tools,').replace('_validate_permission_mode','map_permission_mode').replace('allowed_tools=allowed_tools,','allowed_tools=map_allowed_tools(allowed_tools),')
 put(p,s,'Donor permission/tool signature and SDK option translation hunks only; no run identity/workspace/phase additions')
# Existing presets at already-present consumers.
for rel in ['chains/ralph_loop.py','chains/ralph_workflow.py','chains/remediation.py','chains/ticket_generation.py']:
 p='src/kodezart/'+rel;s=(root/p).read_text();s=s.replace('allowed_tools=EVAL_TOOLS_WITH_AGENT','allowed_tools=ToolPreset.DELEGATED_EVALUATION').replace('allowed_tools=EVAL_TOOLS','allowed_tools=ToolPreset.EVALUATION').replace('allowed_tools=TICKET_TOOLS','allowed_tools=ToolPreset.AUTHORING');s=re.sub(r', EVAL_TOOLS_WITH_AGENT|, EVAL_TOOLS|, TICKET_TOOLS','',s);s=re.sub(r'^    (EVAL_TOOLS_WITH_AGENT|EVAL_TOOLS|TICKET_TOOLS),\n','',s,flags=re.M);i=s.index('from kodezart.');s=s[:i]+'from kodezart.types.domain.session import ToolPreset\n'+s[i:];put(p,s,'Same existing callsite policy mapped to donor ToolPreset; later phase extraction excluded')
p='src/kodezart/adapters/agent_content_scanner.py';s=(root/p).read_text().replace('from kodezart.types.domain.session import SessionType','from kodezart.types.domain.session import PermissionMode, SessionType').replace('_AUDIT_PERMISSION_MODE = "default"','_AUDIT_PERMISSION_MODE = PermissionMode.INTERACTIVE');put(p,s,'Only donor scanner permission constant/import; scanner behavior unchanged')
p='src/kodezart/adapters/git_change_persister.py';s=(root/p).read_text();i=s.index('from kodezart.');s=s[:i]+'from kodezart.types.domain.session import PermissionMode, ToolPreset\n'+s[i:];s=s.replace('permission_mode="plan"','permission_mode=PermissionMode.PLAN').replace('allowed_tools=["Read", "Glob", "Grep", "Bash"]','allowed_tools=ToolPreset.EVALUATION');put(p,s,'Existing commit-message judge exact donor permission/preset only')
p='src/kodezart/types/domain/workflow.py';s=(root/p).read_text();i=s.index('from kodezart.');s=s[:i]+'from kodezart.types.domain.session import AllowedTools, PermissionMode\n'+s[i:];s=s.replace('permission_mode: str = Field(min_length=1)','permission_mode: PermissionMode').replace('allowed_tools: list[str]','allowed_tools: AllowedTools');n=node(p,'WorkflowSubmission');n=re.sub(r'    issue_key: str \| None = None\n|    scope: ScopeRef \| None\n','',n);n=re.sub(r'    """Validated workflow input.*?    """','    """Validated workflow input shared by HTTP and dispatcher producers.\n\n    The producer supplies the recorded base or explicitly constructs a trunk base.\n    """',n,flags=re.S);s=s.replace('class WorkflowContext(CamelCaseModel):',n+'\n\n\nclass WorkflowContext(CamelCaseModel):');put(p,s,'Exact ExecutionContext field types; donor WorkflowSubmission present-base fields only; issue_key/scope deferred M3')
p='src/kodezart/types/requests/agent.py';s=(root/p).read_text().replace('permission_mode: Literal["plan", "bypassPermissions"]','permission_mode: HttpPermissionMode');s=s.replace('class RepoSourceRequest(CamelCaseModel):','HttpPermissionMode = Literal["plan", "bypassPermissions"]\n\n\nclass RepoSourceRequest(CamelCaseModel):');put(p,s,'Exact HTTP alias only; external values/defaults unchanged')
# Queue only accepts validated domain submission; no optional base normalization remains here.
p='src/kodezart/core/protocols.py';s=(root/p).read_text().replace('from kodezart.types.requests.agent import WorkflowRequest','from kodezart.types.domain.workflow import WorkflowSubmission').replace('request: WorkflowRequest','request: WorkflowSubmission');put(p,s,'Agent/session signature closure plus exact JobQueue domain submission type; no tracker/Git/workspace changes')
p='src/kodezart/adapters/asyncio_job_queue.py';s=(root/p).read_text().replace('from kodezart.types.requests.agent import WorkflowRequest','from kodezart.types.domain.workflow import WorkflowSubmission').replace('from kodezart.types.domain.branch import trunk_base\n','').replace('WorkflowRequest','WorkflowSubmission');s=s.replace('base_spec=(\n                    request.base_spec\n                    if request.base_spec is not None\n                    else trunk_base(request.base_branch)\n                )','base_spec=request.base_spec');put(p,s,'Donor submit/storage domain types and normalized base handoff only; queue scheduling/errors unchanged')
p='src/kodezart/handlers/agent_handler.py';s=(root/p).read_text().replace('from kodezart.types.domain.session import SessionType','from kodezart.types.domain.session import PermissionMode, SessionType').replace('from kodezart.types.requests.agent import QueryRequest','from kodezart.types.requests.agent import HttpPermissionMode, QueryRequest, WorkflowRequest\nfrom kodezart.types.domain.workflow import WorkflowSubmission\nfrom kodezart.types.domain.branch import trunk_base');mapping=source(p).split('_HTTP_PERMISSIONS:')[1].split('\n\n\ndef ')[0];s=s.replace('class AgentHandler:','_HTTP_PERMISSIONS:'+mapping+'\n\n\nclass AgentHandler:').replace('permission_mode=request.permission_mode','permission_mode=_HTTP_PERMISSIONS[request.permission_mode]');don=source(p);tree=ast.parse(don);cls=next(n for n in tree.body if isinstance(n,ast.ClassDef) and n.name=='AgentHandler');m=next(n for n in cls.body if getattr(n,'name',None)=='submit_workflow');meth='\n'.join(don.splitlines()[m.lineno-1:m.end_lineno]);meth=re.sub(r'        scope = \(.*?\n        \)\n','',meth,flags=re.S).replace('            issue_key=request.issue_key,\n','').replace('            scope=scope,\n','');s=s.replace('    async def attach_job(',meth+'\n\n    async def attach_job(');put(p,s,'Exact HTTP permission map and present-field donor submit_workflow handler; native scope/issue/egress hunks excluded')
p='src/kodezart/api/v1/endpoints/agent.py';s=(root/p).read_text();s=s.replace('record: JobRecord = await queue.submit(lane=DEFAULT_LANE, request=body)','record: JobRecord = await AgentHandler(\n            service=request.app.state.agent_service,\n            skills=request.app.state.skills,\n            queue=queue,\n        ).submit_workflow(body, lane=DEFAULT_LANE)');put(p,s,'Adapt donor handler entry to existing app.state endpoints; no new dependency subsystem/route/SSE changes')
p='src/kodezart/services/fire_dispatcher.py';s=(root/p).read_text().replace('from kodezart.types.requests.agent import WorkflowRequest','from kodezart.types.domain.workflow import WorkflowSubmission\nfrom kodezart.types.domain.session import PermissionMode, ToolPreset');s=s.replace('request=WorkflowRequest(\n                prompt=context.render(),\n                repo_url=self._repo_url,\n                base_branch=spec.base_branch,\n                base_spec=spec,\n                implied_base=spec,','request=WorkflowSubmission(\n                prompt=context.render(),\n                repo_path=None,\n                repo_url=self._repo_url,\n                base_spec=spec,\n                implied_base=spec,\n                permission_mode=PermissionMode.UNATTENDED,\n                allowed_tools=ToolPreset.IMPLEMENTATION,');put(p,s,'Exact donor domain submission/permission/tool defaults at existing dispatcher; no issue identity/readiness machinery')
Path('/private/tmp/kodezart-recovery-session/session-policy-extraction-operations.json').write_text(json.dumps(manifest,indent=2)+'\n')
