import sys,ast,json
sys.path.insert(0,'/private/tmp/kodezart-recovery-session')
from extract_m2 import *
for name in ['read_issue_revision','project_milestones','execution_approved','_read_execution_approval','read_scope_labels','update_issue_graph','_require_graph_holder','read_split_children','create_split_if_absent','create_criterion_if_absent','read_issue_identity','upsert_issue','edit_description']:
 symbol('tests/fakes.py',name,'FakeTrackerPort')
# Preserve donor graph/native-initialization fake behavior; prior-state receipt is a later milestone.
symbol('tests/fakes.py','_tool_save_issue','FakeLinearMcpServer')
p='tests/fakes.py';text=(T/p).read_text();text=text.replace('        previous_state = (\n            issue.status,\n            issue.status_type,\n            issue.state_changed_at or issue.created_at,\n        )\n','');text=text.replace('        if "state" in arguments:\n            issue.previous_states.append((*previous_state, issue.updated_at))\n            issue.state_changed_at = issue.updated_at\n','');c=node(text,'FakeTrackerPort');lines=text.splitlines(keepends=True);chunk=''.join(lines[start(c):c.end_lineno]);chunk=chunk.replace('        issues: Sequence[TrackerIssue] = (),','        issues: Sequence[TrackerIssue] = (),\n        issue_identities: Mapping[str, IssueIdentity] | None = None,\n        marker_prefixes: Mapping[str, str] | None = None,\n        scope_label_members: Mapping[ScopeRef, frozenset[ScopeLabel]] | None = None,');chunk=chunk.replace('        self.scope_containers:','        self.issue_identities: dict[str, IssueIdentity] = dict(issue_identities or {})\n        self.marker_prefixes: dict[str, str] = dict(marker_prefixes or {})\n        self.scope_label_members = dict(scope_label_members or {})\n        self.issue_creations: list[str] = []\n        self.issue_writes: list[tuple[str, str | None, str | None]] = []\n        self.scope_containers:',1);lines[start(c):c.end_lineno]=[chunk];(T/p).write_text(''.join(lines))
# Scope label settings reach the actual adapter through existing composition.
p='src/kodezart/composition/tracker.py';text=(T/p).read_text();text=text.replace('                issue_labels=operation.issue_labels,','                issue_labels=operation.issue_labels,\n                scope_labels=operation.scope_labels,');(T/p).write_text(text)
f=pathlib.Path('/private/tmp/kodezart-recovery-session/m2-extracted-hunks.json');f.write_text(json.dumps(json.loads(f.read_text())+records,indent=2)+'\n')
