from pathlib import Path
root=Path('/private/tmp/kodezart-v03-recovery-alarm-owner/tests/domain')
def add(s,names):
 return s.replace('from kodezart.types.domain.run_alarm import (','from kodezart.types.domain.run_alarm import (\n    '+',\n    '.join(names)+',',1)
def between(s,start,end,replacement):
 a=s.index(start);b=s.index(end,a);return s[:a]+replacement+s[b:]
p=root/'test_record_consistency.py';s=p.read_text();s=add(s,['CommitsEvidence','CountEvidence','PresenceEvidence','SurfaceEvidence','TextEvidence'])
s=s.replace('value=json.dumps(json.loads(surface_alarm_member_id(address)), indent=2)','value=SurfaceEvidence(value=address)').replace('value=json.dumps(present)','value=PresenceEvidence(value=present)')
s=s.replace('value=json.dumps(value, indent=2)','value=value').replace('for value in ("lane/42", head, count, rows)','for value in (TextEvidence(value="lane/42"), TextEvidence(value=head), CountEvidence(value=count), CommitsEvidence(value=tuple(LaneCommit.model_validate(row) for row in rows)))')
p.write_text(s)
p=root/'test_record_superseded.py';s=p.read_text();s=add(s,['LaneFieldEvidence','ReferencesEvidence'])
s=s.replace('value=json.dumps(assertion(record_value), indent=2)','value=LaneFieldEvidence(value=LaneFieldValue.model_validate(assertion(record_value)))').replace('value=json.dumps(assertion(event_value), indent=2)','value=LaneFieldEvidence(value=LaneFieldValue.model_validate(assertion(event_value)))').replace('value=json.dumps(order, indent=2)','value=ReferencesEvidence(value=order)')
s=s.replace('value=json.dumps(tuple(reversed(ORDER)))','value=ReferencesEvidence(value=tuple(reversed(ORDER)))').replace('value=json.dumps(body)','value=LaneFieldEvidence(value=LaneFieldValue.model_validate(body))').replace('value=json.dumps(order)','value=ReferencesEvidence(value=order)')
s=s.replace('value=json.dumps(\n            {"value": value, "fieldKey": "quality_gate", "laneKey": "lane/42"},\n            ensure_ascii=False,\n        )','value=LaneFieldEvidence(value=LaneFieldValue(value=value, field_key="quality_gate", lane_key="lane/42"))')
p.write_text(s)
p=root/'test_surface_contention.py';s=p.read_text();s=add(s,['CountEvidence','ReferencesEvidence','SurfaceEvidence'])
s=s.replace('value=SURFACE_JSON.dump_json(surface, indent=2).decode()','value=SurfaceEvidence(value=surface)').replace('value=json.dumps(holders, indent=2)','value=ReferencesEvidence(value=holders)').replace('value=json.dumps(limit)','value=CountEvidence(value=limit)')
p.write_text(s)
p=root/'test_barren_tick.py';s=p.read_text();s=add(s,['CountEvidence','ReferencesEvidence'])
s=s.replace('value=json.dumps(value, indent=2)','value=value')
for expr in ['previous','closed']:
 s=s.replace(', '+expr+',',', ReferencesEvidence(value='+expr+'),')
for expr in ['files','commits','max_files','max_commits']:
 s=s.replace(', '+expr+',',', CountEvidence(value='+expr+'),')
p.write_text(s)
p=root/'test_escalation_ageing.py';s=p.read_text();s=add(s,['CountEvidence','EscalationEvidence','ResolutionEvidence','ReferencesEvidence'])
s=s.replace('from kodezart.domain.errors import RunShapeReadError','from kodezart.domain.errors import RunShapeReadError\nfrom kodezart.types.domain.run_state import LaneEscalation\nfrom kodezart.types.domain.escalation import EscalationResolution, EscalationResolutionState')
s=s.replace('value=json.dumps(escalation, indent=2)','value=EscalationEvidence(value=LaneEscalation.model_validate(escalation))')
s=s.replace('value=json.dumps(\n                {\n                    "state": "resolved" if resolved else "unresolved",\n                    "decisionRef": "comment/decision" if resolved else None,\n                }\n            )','value=ResolutionEvidence(value=EscalationResolution(state=EscalationResolutionState.RESOLVED if resolved else EscalationResolutionState.UNRESOLVED, decision_ref="comment/decision" if resolved else None))')
s=s.replace('value=json.dumps(commits, indent=2)','value=ReferencesEvidence(value=commits)')
for expr in ['ticks','max_commits','max_ticks']:
 s=s.replace('value=json.dumps('+expr+')','value=CountEvidence(value='+expr+')')
p.write_text(s)
p=root/'test_scope_tally.py';s=p.read_text();s=add(s,['LabelsEvidence','ReferencesEvidence','ScopeEvidence','TextEvidence'])
s=s.replace('def reading(source, value):\n    return AlarmReading(source_ref=source, value=json.dumps(value))','def reading(source, value):\n    return AlarmReading(source_ref=source, value=value)')
s=s.replace('value=SCOPE.model_dump_json()','value=ScopeEvidence(value=SCOPE)')
s=s.replace('reading(TICKET_MARKER_SOURCE, "issue_labels.body-ready")','reading(TICKET_MARKER_SOURCE, TextEvidence(value="issue_labels.body-ready"))').replace('reading(CRITERIA_MARKER_SOURCE, "issue_labels.criteria-ready")','reading(CRITERIA_MARKER_SOURCE, TextEvidence(value="issue_labels.criteria-ready"))')
s=s.replace('reading(SCOPE.key, roster)','reading(SCOPE.key, ReferencesEvidence(value=roster))').replace('reading(key, value) for key, value in labels.items()','reading(key, LabelsEvidence(value=None if value is None else tuple(value))) for key, value in labels.items()')
# Damaged semantic identities remain explicitly typed values.
import re
s=re.sub(r'reading\(([^,\n]+), ("[^"\n]*")\)',r'reading(\1, TextEvidence(value=\2))',s)
s=s.replace('reading("elsewhere", ["one", "two"])','reading("elsewhere", ReferencesEvidence(value=("one", "two")))')
s=s.replace('reading(SCOPE.key, {"kind": "project", "key": "foreign"})','reading(SCOPE.key, ScopeEvidence(value=ScopeRef(kind=ScopeKind.PROJECT, key="foreign")))')
s=s.replace('reading(SCOPE.key, ["one", "two", "one"])','reading(SCOPE.key, ReferencesEvidence(value=("one", "two", "one")))')
s=s.replace('reading("foreign", ["criteria-ready"])','reading("foreign", LabelsEvidence(value=("criteria-ready",)))').replace('reading("one", ["body-ready"])','reading("one", LabelsEvidence(value=("body-ready",)))')
s=s.replace('value="not JSON"','value=TextEvidence(value="wrong evidence arm")')
s=s.replace('reading(SCOPE.key, [""])','reading(SCOPE.key, TextEvidence(value="wrong evidence arm"))').replace('reading(TICKET_MARKER_SOURCE, [])','reading(TICKET_MARKER_SOURCE, LabelsEvidence(value=()))')
p.write_text(s)
p=root/'test_mandate_graph.py';s=p.read_text();s=add(s,['CountEvidence','GraphEvidence','ReferencesEvidence','RulingsEvidence'])
s=s.replace('    LaneGraphSnapshot,','    LaneGraphSnapshot,\n    LaneRulingSnapshot,')
s=s.replace('def reading(value: object, source: str = "lane-record") -> AlarmReading:\n    return AlarmReading(source_ref=source, value=json.dumps(value))','def reading(value, source: str = "lane-record") -> AlarmReading:\n    return AlarmReading(source_ref=source, value=value)')
s=s.replace('reading(ruling_snapshot(baseline or []))','reading(RulingsEvidence(value=LaneRulingSnapshot.model_validate(ruling_snapshot(baseline or []))))')
s=s.replace('reading(\n            ruling_snapshot(rows if rows is not None else [ruling("a"), ruling("b")])\n        )','reading(RulingsEvidence(value=LaneRulingSnapshot.model_validate(ruling_snapshot(rows if rows is not None else [ruling("a"), ruling("b")]))))')
s=s.replace('reading(["criterion/open"])','reading(ReferencesEvidence(value=("criterion/open",)))').replace('reading(closed)','reading(ReferencesEvidence(value=closed))').replace('reading(bound, RULINGS_BOUND)','reading(CountEvidence(value=bound), RULINGS_BOUND)')
s=s.replace('value=snapshot.model_dump_json()','value=GraphEvidence(value=snapshot)')
s=s.replace('reading({"laneKey": "lane", "issueKeys": ["FIRE"], "rulings": [row]})','reading(RulingsEvidence(value=LaneRulingSnapshot.model_validate({"laneKey": "lane", "issueKeys": ["FIRE"], "rulings": [row]})))')
p.write_text(s)
