"""Prompt bodies the criteria lifecycle renders — pure, no I/O.

The one owner of text written FOR the criteria agents, as distinct from
:mod:`kodezart.domain.prompt_variables`, which binds render variables for
the evaluation template.  A regeneration round is the only reader today.
"""

from collections.abc import Sequence

from kodezart.types.domain.criteria import (
    CriteriaValidation,
    CriterionVerdict,
    GeneratedCriterion,
)


def render_validation_findings(
    criteria: Sequence[GeneratedCriterion],
    validation: CriteriaValidation | None,
) -> str | None:
    """The ``<validation_findings>`` body for a regeneration round.

    Only criteria the sweep asked to AMEND appear: ``infeasible`` verdicts
    and the members of each unsatisfiable conjunction.  An ``unverifiable``
    criterion is regenerated by nobody, so naming it here would re-enter
    through the prompt the collapse the three-state verdict exists to stop.

    ``None`` when the sweep asked for nothing.
    """
    if validation is None:
        return None
    texts = {criterion.id: criterion.text for criterion in criteria}
    lines: list[str] = []
    for verdict in validation.verdicts:
        if verdict.verdict is not CriterionVerdict.infeasible:
            continue
        text = texts.get(verdict.criterion_id, "")
        lines.append(
            f"{verdict.criterion_id} infeasible: {text}\n"
            f"  refutation: {verdict.refutation}"
        )
    lines.extend(
        f"conjunction unsatisfiable over "
        f"{', '.join(contradiction.criterion_ids)}: {contradiction.explanation}"
        for contradiction in validation.conjunction.contradictions
    )
    if not lines:
        return None
    return "\n".join(lines)
