"""Per-call render variables derived from domain values — pure, no I/O."""

from collections.abc import Sequence

from kodezart.types.domain.consolidation import ChangesetDigest
from kodezart.types.domain.criteria import (
    CriteriaValidation,
    CriterionVerdict,
    GeneratedCriterion,
)


def changeset_variables(changeset: ChangesetDigest) -> dict[str, object]:
    """Render variables for the changeset section of an evaluation template.

    The empty / non-empty split is expressed as PRESENCE of a variable,
    matching the renderer's ``{{#if}}``: a name is bound only when its
    section applies.
    """
    variables: dict[str, object] = {
        "commit_count": changeset.commit_count,
        "file_paths": changeset.file_paths,
        "commit_subjects": changeset.commit_subjects,
    }
    if changeset.is_empty:
        variables["changeset_is_empty"] = True
    else:
        variables["changeset_has_commits"] = True
    if not changeset.file_paths:
        variables["file_paths_absent"] = True
    return variables


def render_validation_findings(
    criteria: Sequence[GeneratedCriterion],
    validation: CriteriaValidation | None,
) -> str | None:
    """The ``<validation_findings>`` body for a regeneration round.

    Only criteria the sweep asked to AMEND appear: ``infeasible`` verdicts
    and the members of each unsatisfiable conjunction.  An ``unverifiable``
    criterion is regenerated by nobody, so naming it here would re-enter
    through the prompt the collapse the three-state verdict exists to stop.

    ``None`` when the sweep asked for nothing.
    """
    if validation is None:
        return None
    texts = {criterion.id: criterion.text for criterion in criteria}
    lines: list[str] = []
    for verdict in validation.verdicts:
        if verdict.verdict is not CriterionVerdict.infeasible:
            continue
        text = texts.get(verdict.criterion_id, "")
        lines.append(
            f"{verdict.criterion_id} infeasible: {text}\n"
            f"  refutation: {verdict.refutation}"
        )
    lines.extend(
        f"conjunction unsatisfiable over "
        f"{', '.join(contradiction.criterion_ids)}: {contradiction.explanation}"
        for contradiction in validation.conjunction.contradictions
    )
    if not lines:
        return None
    return "\n".join(lines)
