"""Per-call render variables derived from domain values — pure, no I/O."""

from collections.abc import Sequence

from kodezart.types.domain.consolidation import ChangesetDigest
from kodezart.types.domain.criteria import (
    AcceptanceCriterion,
    CriteriaValidation,
    FeasibilityVerdict,
)


def changeset_variables(changeset: ChangesetDigest) -> dict[str, object]:
    """Render variables for the changeset section of an evaluation template.

    The empty / non-empty split and the "(none)" file-list case are expressed
    as PRESENCE of a variable, matching the renderer's presence-conditional
    ``{{#if}}``: a name is bound only when its section applies.
    """
    variables: dict[str, object] = {
        "commit_count": changeset.commit_count,
        "file_paths": changeset.file_paths,
        "commit_subjects": changeset.commit_subjects,
    }
    if changeset.is_empty:
        variables["changeset_is_empty"] = True
    else:
        variables["changeset_has_commits"] = True
    if not changeset.file_paths:
        variables["file_paths_absent"] = True
    return variables


def render_validation_findings(
    criteria: Sequence[AcceptanceCriterion],
    validation: CriteriaValidation | None,
) -> str | None:
    """The ``<validation_findings>`` body for a regeneration round.

    Only criteria the sweep asked to AMEND appear: ``infeasible`` verdicts
    and the members of an unsatisfiable conjunction.  An ``unverifiable``
    criterion is regenerated by nobody, so naming it here would re-enter
    through the prompt exactly the collapse the verdict schema forbids.

    ``None`` when the sweep asked for nothing, so the template's presence
    conditional stays closed on the first round.
    """
    if validation is None:
        return None
    texts = {criterion.id: criterion.text for criterion in criteria}
    conflicting = set(validation.conjunction.conflicting_ids)
    lines: list[str] = []
    for verdict in validation.verdicts:
        if verdict.verdict is not FeasibilityVerdict.infeasible:
            continue
        text = texts.get(verdict.criterion_id, "")
        lines.append(
            f"{verdict.criterion_id} infeasible: {text}\n"
            f"  refutation: {verdict.refutation}"
        )
    if conflicting:
        named = ", ".join(validation.conjunction.conflicting_ids)
        lines.append(
            f"conjunction unsatisfiable over {named}: "
            f"{validation.conjunction.explanation}"
        )
    if not lines:
        return None
    return "\n".join(lines)
