"""Agent event domain models for SSE streaming."""

from typing import Literal

from pydantic import (
    ConfigDict,
    Field,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer,
)

from kodezart.types.base import CamelCaseModel
from kodezart.types.domain.accept import AcceptVerdict, SherlockFlag
from kodezart.types.domain.base_spec import BaseInput, BaseRefRole
from kodezart.types.domain.consolidation import ConsolidationStatus
from kodezart.types.domain.criteria import (
    CRITERION_ID_PATTERN,
    CriteriaValidation,
    CriteriaValidationOutput,
    CriterionId,
    DraftedCriterion,
    GeneratedCriterion,
)
from kodezart.types.domain.gating import RepoVisibility
from kodezart.types.domain.outcome import WorkflowOutcome
from kodezart.types.domain.trajectory import LoopTrajectory

# ---------------------------------------------------------------------------
# Soft-failure raise-site identifier (typed alias)
# ---------------------------------------------------------------------------
#
# ``RaiseSite`` is defined here — the upstream end of the dependency
# chain — so that both ``types/domain/agent.ErrorEvent`` and
# ``core/errors.NoStructuredOutputError`` can refer to the SAME typed
# alias.  ``core/errors.py`` imports ``RaiseSite`` from this
# module; ``ErrorEvent.raise_site`` references it directly.  Drift
# between two parallel ``Literal`` lists is structurally impossible.

RaiseSite = Literal[
    "ticket_creator",
    "ticket_reviewer",
    "branch_name",
    "acceptance_criteria",
    "criteria_validation",
    "ralph_evaluator",
    "post_merge_review",
    "pr_description",
    "commit_message",
]

# ---------------------------------------------------------------------------
# Ticket-generation structured outputs
# ---------------------------------------------------------------------------


class CodeReference(CamelCaseModel):
    """A reference to a specific location in the codebase."""

    location: str = Field(min_length=1)
    note: str = Field(min_length=1)


class FileChange(CamelCaseModel):
    """A single file-level change required to implement the ticket."""

    file_path: str = Field(min_length=1)
    change_type: Literal["create", "modify", "delete"]
    description: str = Field(min_length=1)
    rationale: str = Field(min_length=1)


class TicketDraftOutput(CamelCaseModel):
    """Structured output for a generated implementation ticket.

    The downstream generate_criteria agent has its own job — it derives
    observable acceptance criteria from the full formatted ticket.
    """

    title: str = Field(min_length=1, max_length=120)
    summary: str = Field(min_length=1)
    context: str = Field(min_length=1)
    references: list[CodeReference] = Field(default_factory=list)
    required_changes: list[FileChange] = Field(min_length=1)
    out_of_scope: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)


class TicketReviewOutput(CamelCaseModel):
    """Structured output for a ticket review."""

    approved: bool
    feedback: str = Field(min_length=1)
    suggestions: list[str] = Field(default_factory=list)


class AgentEvent(CamelCaseModel):
    """Base SSE event. ``type`` discriminates variants."""

    type: str


class TaskUsageInfo(CamelCaseModel):
    """Token usage and timing metadata for a sub-task."""

    total_tokens: int
    tool_uses: int
    duration_ms: int


class UserMessageEvent(AgentEvent):
    """User message echoed back in the SSE stream."""

    type: Literal["user_message"] = "user_message"
    content: str

    @field_validator("content", mode="before")
    @classmethod
    def _coerce_to_str(cls, v: object) -> str:
        return v if isinstance(v, str) else str(v)


class AssistantTextEvent(AgentEvent):
    """Text content generated by Claude."""

    type: Literal["assistant_text"] = "assistant_text"
    text: str
    model: str


class AssistantThinkingEvent(AgentEvent):
    """Extended thinking content from Claude."""

    type: Literal["assistant_thinking"] = "assistant_thinking"
    thinking: str
    model: str


class ToolUseEvent(AgentEvent):
    """Agent requesting a tool invocation."""

    type: Literal["tool_use"] = "tool_use"
    name: str
    input: dict[str, object]
    id: str
    model: str


class ToolResultEvent(AgentEvent):
    """Result returned from a tool invocation."""

    type: Literal["tool_result"] = "tool_result"
    content: str | list[dict[str, object]] | None = None
    tool_use_id: str
    is_error: bool | None = None


class SystemEvent(AgentEvent):
    """System-level event from the Claude SDK."""

    type: Literal["system"] = "system"
    subtype: str
    data: dict[str, object]


class TaskStartedEvent(AgentEvent):
    """Sub-task spawned by the agent."""

    type: Literal["task_started"] = "task_started"
    subtype: str
    task_id: str
    description: str
    uuid: str
    session_id: str
    tool_use_id: str | None = None
    task_type: str | None = None
    data: dict[str, object]


class TaskProgressEvent(AgentEvent):
    """Progress update from a running sub-task."""

    type: Literal["task_progress"] = "task_progress"
    subtype: str
    task_id: str
    description: str
    usage: TaskUsageInfo
    uuid: str
    session_id: str
    tool_use_id: str | None = None
    last_tool_name: str | None = None
    data: dict[str, object]


class TaskNotificationEvent(AgentEvent):
    """Completion notification from a sub-task."""

    type: Literal["task_notification"] = "task_notification"
    subtype: str
    task_id: str
    status: Literal["completed", "failed", "stopped"]
    output_file: str
    summary: str
    uuid: str
    session_id: str
    tool_use_id: str | None = None
    usage: TaskUsageInfo | None = None
    data: dict[str, object]


class ResultEvent(AgentEvent):
    """Terminal event with metrics, session ID, and output."""

    type: Literal["result"] = "result"
    subtype: str
    duration_ms: int
    duration_api_ms: int
    is_error: bool
    num_turns: int
    session_id: str
    stop_reason: str | None = None
    total_cost_usd: float | None = None
    usage: dict[str, object] | None = None
    result: str | None = None
    branch: str | None = None
    commit_sha: str | None = None
    structured_output: dict[str, object] | None = None


class StreamDataEvent(AgentEvent):
    """Raw SDK stream event forwarded for transparency."""

    type: Literal["stream_event"] = "stream_event"
    session_id: str
    event: dict[str, object]


class ErrorEvent(AgentEvent):
    """Error event emitted on agent or workspace failure.

    Wire shape locked with ``extra="forbid"`` — a future field-name
    typo on the producer side raises at validation time rather than
    silently breaking downstream SSE consumers.

    The typed optional fields below promote the genuinely consumed
    observability slots to top-level named attributes, replacing the
    previous draft's ``details: dict[str, object]`` bag.  Each is
    independently type-checkable by downstream consumers.

    The ``raise_site`` field references the ``RaiseSite`` typed alias
    defined above in this module.  ``core/errors.py`` imports
    the SAME alias, so the eight-literal enumeration has exactly one
    authoritative definition and any future addition is enforced
    everywhere by ``mypy``.
    """

    model_config = ConfigDict(extra="forbid")

    type: Literal["error"] = "error"
    error: str
    error_kind: str | None = None
    cause_class: str | None = None
    stop_reason: str | None = None
    raise_site: RaiseSite | None = None
    rate_limit_rejected: bool | None = None
    exit_code: int | None = None
    stderr_tail: str | None = None


class RateLimitWarningEvent(AgentEvent):
    """Emitted when the Claude SDK reports a rate-limit warning or rejection."""

    type: Literal["rate_limit_warning"] = "rate_limit_warning"
    status: Literal["allowed_warning", "rejected"]
    resets_at: int | None = None
    utilization: float | None = None
    rate_limit_type: str | None = None


class CommitMessageOutput(CamelCaseModel):
    """Structured output schema for agent-generated commit messages."""

    title: str = Field(min_length=1, max_length=72)
    body: str = Field(default="")


class CriterionResult(CamelCaseModel):
    """Per-criterion evaluation result, keyed by the harness's stable id.

    ``criterion`` is the evaluator's ECHO of the criterion text and is
    carried only so a reader can see what the model believed it was
    grading.  Nothing keys off it: identity is ``criterion_id``, and the
    text the harness re-injects is its own, looked up by that id.
    """

    model_config = ConfigDict(frozen=True, populate_by_name=True)

    criterion_id: CriterionId = Field(pattern=CRITERION_ID_PATTERN)
    criterion: str = Field(min_length=1)
    passed: bool
    reasoning: str = Field(min_length=1)


class AcceptanceCriteriaOutput(CamelCaseModel):
    """Structured output for acceptance criteria evaluation.

    ``sherlock_flags`` carries the synthesis's own concerns as data.  A
    reasoning error the evaluator noticed but could only write into prose
    is invisible to every consumer downstream of it; as a typed field it
    rides the iteration event and reaches the pull-request body.
    """

    criteria_results: list[CriterionResult] = Field(min_length=1)
    sherlock_flags: list[SherlockFlag] = Field(default_factory=list)


class BranchNameOutput(CamelCaseModel):
    """Agent-generated branch name slug."""

    slug: str = Field(min_length=1, max_length=50)


class GeneratedCriteriaOutput(CamelCaseModel):
    """Agent-generated acceptance criteria from ticket + codebase analysis.

    Identity is NOT part of this shape — ``AC-n`` ids are minted
    harness-side from emission order, so a regeneration round cannot
    renumber a criterion by echoing a different id.
    """

    criteria: list[DraftedCriterion] = Field(min_length=1)
    reasoning: str = Field(min_length=1)


class PRDescriptionOutput(CamelCaseModel):
    """Structured output for agent-generated PR descriptions."""

    title: str = Field(min_length=1, max_length=120)
    description: str = Field(min_length=1)


class WorkflowReviewEvent(AgentEvent):
    """Emitted after post-merge review against ticket criteria."""

    type: Literal["workflow_review"] = "workflow_review"
    passed: bool
    evaluation: AcceptanceCriteriaOutput
    fix_round: int


class WorkflowPREvent(AgentEvent):
    """Emitted after a pull request is opened."""

    type: Literal["workflow_pr"] = "workflow_pr"
    pr_url: str
    pr_number: int
    feature_branch: str
    base_branch: str


class WorkflowCIEvent(AgentEvent):
    """Emitted after CI monitoring completes or is skipped."""

    type: Literal["workflow_ci"] = "workflow_ci"
    passed: bool | None
    summary: str
    ref: str

    @model_serializer(mode="wrap")
    def _force_ci_field(
        self,
        handler: SerializerFunctionWrapHandler,
    ) -> dict[str, object]:
        result: dict[str, object] = handler(self)
        if "passed" not in result:
            result["passed"] = None
        return result


class WorkflowIterationEvent(AgentEvent):
    """Emitted after each ralph loop iteration.

    ``trajectory`` is the loop's progress memory folded over every
    iteration so far.  It is required — the loop→workflow seam carries
    it on this existing channel rather than on a second event type.

    ``verdict`` is three-state.  It replaced a boolean ``accepted``:
    a run whose only failures are soft signals ships AND has something to
    say, and no boolean could carry both.
    """

    type: Literal["workflow_iteration"] = "workflow_iteration"
    iteration: int
    branch: str
    commit_sha: str | None = None
    verdict: AcceptVerdict
    evaluation: AcceptanceCriteriaOutput
    trajectory: LoopTrajectory


class WorkflowConsolidationEvent(AgentEvent):
    """Emitted after every `BranchMerger.consolidate(...)` call.

    Reports the four-way outcome (``ALREADY_INTEGRATED``,
    ``FAST_FORWARDED``, ``DIVERGENT``, ``SOURCE_MISSING``) without
    routing semantics — routing lives in the workflow graph's
    conditional edges, not on this event.  No ``phase`` field: both
    emission sites (post-loop and post-fix) are distinguished by
    event ordering relative to ``WorkflowReviewEvent``.
    """

    type: Literal["workflow_consolidation"] = "workflow_consolidation"
    status: ConsolidationStatus
    feature_branch: str = Field(min_length=1)
    source_branch: str = Field(min_length=1)
    feature_tip_sha: str = Field(min_length=40, max_length=40)


class WorkflowCompleteEvent(AgentEvent):
    """Emitted when the ralph loop finishes.

    ``outcome`` is the sole terminal discriminator — required and
    non-nullable, so ``exclude_none=True`` can never drop it and no
    serializer hack is needed to force it onto the wire.
    """

    type: Literal["workflow_complete"] = "workflow_complete"
    feature_branch: str
    ralph_branch: str
    total_iterations: int
    accepted: bool
    outcome: WorkflowOutcome
    merged: bool = False
    final_commit_sha: str | None = None
    error: str | None = None
    pr_url: str | None = None
    pr_number: int | None = None
    ci_passed: bool | None = None
    trajectory: LoopTrajectory | None = None
    criteria_validation: CriteriaValidation | None = None

    @model_serializer(mode="wrap")
    def _force_ci_field(
        self,
        handler: SerializerFunctionWrapHandler,
    ) -> dict[str, object]:
        result: dict[str, object] = handler(self)
        # ci_passed is a three-state field (True/False/None) — must always appear
        key = "ciPassed" if "featureBranch" in result else "ci_passed"
        if key not in result:
            result[key] = None
        return result


class WorkflowVisibilityEvent(AgentEvent):
    """Emitted once per run when repository visibility is resolved."""

    type: Literal["workflow_visibility"] = "workflow_visibility"
    visibility: RepoVisibility
    repo_url: str | None = None


class WorkflowScopeBaseEvent(AgentEvent):
    """Emitted once per run: the ref every scope comparison is made against.

    A maintainer reading a run's events can confirm which ref the scope
    and no-touch checks compared against, and — on a constructed base —
    which blockers it was built from.  Without this the baseline is only
    visible by inference from a diff, which is exactly how a wrong one
    went unnoticed.
    """

    type: Literal["workflow_scope_base"] = "workflow_scope_base"
    base_ref: str
    role: BaseRefRole
    inputs: list[BaseInput] = Field(default_factory=list)


class JobAcceptedEvent(AgentEvent):
    """Leading frame of an attached run — carries the reconnect handle.

    A client that drops mid-run reconnects at ``stream_url`` with this
    ``job_id`` instead of losing the run.
    """

    type: Literal["job_accepted"] = "job_accepted"
    job_id: str
    lane: str
    queue_position: int
    status_url: str
    stream_url: str


class WorkflowCriteriaEvent(AgentEvent):
    """Emitted after acceptance criteria are generated from ticket analysis."""

    type: Literal["workflow_criteria"] = "workflow_criteria"
    criteria: list[GeneratedCriterion]
    reasoning: str


class WorkflowCriteriaValidationEvent(AgentEvent):
    """Emitted after every feasibility sweep over a generated criteria set."""

    type: Literal["workflow_criteria_validation"] = "workflow_criteria_validation"
    regeneration_round: int
    validation: CriteriaValidation
    regeneration_targets: list[str]


class WorkflowTicketDraftEvent(AgentEvent):
    """Emitted after each ticket draft iteration."""

    type: Literal["workflow_ticket_draft"] = "workflow_ticket_draft"
    iteration: int
    draft: TicketDraftOutput


class WorkflowTicketReviewEvent(AgentEvent):
    """Emitted after each ticket review iteration."""

    type: Literal["workflow_ticket_review"] = "workflow_ticket_review"
    iteration: int
    approved: bool
    feedback: str
    suggestions: list[str]


class WorkflowTicketEvent(AgentEvent):
    """Emitted when ticket generation finishes."""

    type: Literal["workflow_ticket"] = "workflow_ticket"
    ticket: TicketDraftOutput
    review_rounds: int
    approved: bool


# Pre-computed JSON schemas for structured agent output via output_format
COMMIT_MESSAGE_SCHEMA: dict[str, object] = CommitMessageOutput.model_json_schema()
# Schema for acceptance criteria evaluation results
ACCEPTANCE_CRITERIA_SCHEMA: dict[str, object] = (
    AcceptanceCriteriaOutput.model_json_schema()
)
# Schema for agent-generated branch name slugs
BRANCH_NAME_SCHEMA: dict[str, object] = BranchNameOutput.model_json_schema()
# Schema for agent-generated acceptance criteria from ticket analysis
GENERATED_CRITERIA_SCHEMA: dict[str, object] = (
    GeneratedCriteriaOutput.model_json_schema()
)
# Schema for the feasibility sweep's per-criterion findings
CRITERIA_VALIDATION_SCHEMA: dict[str, object] = (
    CriteriaValidationOutput.model_json_schema()
)
# Schema for structured ticket draft output
TICKET_DRAFT_SCHEMA: dict[str, object] = TicketDraftOutput.model_json_schema()
# Schema for structured ticket review output
TICKET_REVIEW_SCHEMA: dict[str, object] = TicketReviewOutput.model_json_schema()
PR_DESCRIPTION_SCHEMA: dict[str, object] = PRDescriptionOutput.model_json_schema()
