"""Agent event domain models for SSE streaming."""

from typing import Literal

from pydantic import (
    ConfigDict,
    Field,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer,
)

from kodezart.types.base import CamelCaseModel

# ---------------------------------------------------------------------------
# Ticket-generation structured outputs
# ---------------------------------------------------------------------------


class CodeReference(CamelCaseModel):
    """A reference to a specific location in the codebase."""

    location: str = Field(min_length=1)
    note: str = Field(min_length=1)


class FileChange(CamelCaseModel):
    """A single file-level change required to implement the ticket."""

    file_path: str = Field(min_length=1)
    change_type: Literal["create", "modify", "delete"]
    description: str = Field(min_length=1)
    rationale: str = Field(min_length=1)


class TicketDraftOutput(CamelCaseModel):
    """Structured output for a generated implementation ticket.

    The downstream generate_criteria agent has its own job — it derives
    observable acceptance criteria from the full formatted ticket.
    """

    title: str = Field(min_length=1, max_length=120)
    summary: str = Field(min_length=1)
    context: str = Field(min_length=1)
    references: list[CodeReference] = Field(default_factory=list)
    required_changes: list[FileChange] = Field(min_length=1)
    out_of_scope: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)


class TicketReviewOutput(CamelCaseModel):
    """Structured output for a ticket review."""

    approved: bool
    feedback: str = Field(min_length=1)
    suggestions: list[str] = Field(default_factory=list)


class AgentEvent(CamelCaseModel):
    """Base SSE event. ``type`` discriminates variants."""

    type: str


class TaskUsageInfo(CamelCaseModel):
    """Token usage and timing metadata for a sub-task."""

    total_tokens: int
    tool_uses: int
    duration_ms: int


class UserMessageEvent(AgentEvent):
    """User message echoed back in the SSE stream."""

    type: Literal["user_message"] = "user_message"
    content: str

    @field_validator("content", mode="before")
    @classmethod
    def _coerce_to_str(cls, v: object) -> str:
        return v if isinstance(v, str) else str(v)


class AssistantTextEvent(AgentEvent):
    """Text content generated by Claude."""

    type: Literal["assistant_text"] = "assistant_text"
    text: str
    model: str


class AssistantThinkingEvent(AgentEvent):
    """Extended thinking content from Claude."""

    type: Literal["assistant_thinking"] = "assistant_thinking"
    thinking: str
    model: str


class ToolUseEvent(AgentEvent):
    """Agent requesting a tool invocation."""

    type: Literal["tool_use"] = "tool_use"
    name: str
    input: dict[str, object]
    id: str
    model: str


class ToolResultEvent(AgentEvent):
    """Result returned from a tool invocation."""

    type: Literal["tool_result"] = "tool_result"
    content: str | list[dict[str, object]] | None = None
    tool_use_id: str
    is_error: bool | None = None


class SystemEvent(AgentEvent):
    """System-level event from the Claude SDK."""

    type: Literal["system"] = "system"
    subtype: str
    data: dict[str, object]


class TaskStartedEvent(AgentEvent):
    """Sub-task spawned by the agent."""

    type: Literal["task_started"] = "task_started"
    subtype: str
    task_id: str
    description: str
    uuid: str
    session_id: str
    tool_use_id: str | None = None
    task_type: str | None = None
    data: dict[str, object]


class TaskProgressEvent(AgentEvent):
    """Progress update from a running sub-task."""

    type: Literal["task_progress"] = "task_progress"
    subtype: str
    task_id: str
    description: str
    usage: TaskUsageInfo
    uuid: str
    session_id: str
    tool_use_id: str | None = None
    last_tool_name: str | None = None
    data: dict[str, object]


class TaskNotificationEvent(AgentEvent):
    """Completion notification from a sub-task."""

    type: Literal["task_notification"] = "task_notification"
    subtype: str
    task_id: str
    status: Literal["completed", "failed", "stopped"]
    output_file: str
    summary: str
    uuid: str
    session_id: str
    tool_use_id: str | None = None
    usage: TaskUsageInfo | None = None
    data: dict[str, object]


class ResultEvent(AgentEvent):
    """Terminal event with metrics, session ID, and output."""

    type: Literal["result"] = "result"
    subtype: str
    duration_ms: int
    duration_api_ms: int
    is_error: bool
    num_turns: int
    session_id: str
    stop_reason: str | None = None
    total_cost_usd: float | None = None
    usage: dict[str, object] | None = None
    result: str | None = None
    branch: str | None = None
    commit_sha: str | None = None
    structured_output: dict[str, object] | None = None


class StreamDataEvent(AgentEvent):
    """Raw SDK stream event forwarded for transparency."""

    type: Literal["stream_event"] = "stream_event"
    session_id: str
    event: dict[str, object]


class ErrorEvent(AgentEvent):
    """Error event emitted on agent or workspace failure."""

    type: Literal["error"] = "error"
    error: str


class RateLimitWarningEvent(AgentEvent):
    """Emitted when the Claude SDK reports a rate-limit warning or rejection."""

    type: Literal["rate_limit_warning"] = "rate_limit_warning"
    status: Literal["allowed_warning", "rejected"]
    resets_at: int | None = None
    utilization: float | None = None
    rate_limit_type: str | None = None


class CommitMessageOutput(CamelCaseModel):
    """Structured output schema for agent-generated commit messages."""

    title: str = Field(min_length=1, max_length=72)
    body: str = Field(default="")


class CriterionResult(CamelCaseModel):
    """Per-criterion evaluation result with evaluator reasoning."""

    model_config = ConfigDict(frozen=True, populate_by_name=True)

    criterion: str = Field(min_length=1)
    passed: bool
    reasoning: str = Field(min_length=1)


class AcceptanceCriteriaOutput(CamelCaseModel):
    """Structured output for acceptance criteria evaluation."""

    criteria_results: list[CriterionResult] = Field(min_length=1)


class BranchNameOutput(CamelCaseModel):
    """Agent-generated branch name slug."""

    slug: str = Field(min_length=1, max_length=50)


class GeneratedCriteriaOutput(CamelCaseModel):
    """Agent-generated acceptance criteria from ticket + codebase analysis."""

    criteria: list[str] = Field(min_length=1)
    reasoning: str = Field(min_length=1)


class PRDescriptionOutput(CamelCaseModel):
    """Structured output for agent-generated PR descriptions."""

    title: str = Field(min_length=1, max_length=120)
    description: str = Field(min_length=1)


class WorkflowReviewEvent(AgentEvent):
    """Emitted after post-merge review against ticket criteria."""

    type: Literal["workflow_review"] = "workflow_review"
    passed: bool
    evaluation: AcceptanceCriteriaOutput
    fix_round: int


class WorkflowPREvent(AgentEvent):
    """Emitted after a pull request is opened."""

    type: Literal["workflow_pr"] = "workflow_pr"
    pr_url: str
    pr_number: int
    feature_branch: str
    base_branch: str


class WorkflowCIEvent(AgentEvent):
    """Emitted after CI monitoring completes or is skipped."""

    type: Literal["workflow_ci"] = "workflow_ci"
    passed: bool | None
    summary: str
    ref: str

    @model_serializer(mode="wrap")
    def _force_ci_field(
        self,
        handler: SerializerFunctionWrapHandler,
    ) -> dict[str, object]:
        result: dict[str, object] = handler(self)
        if "passed" not in result:
            result["passed"] = None
        return result


class WorkflowIterationEvent(AgentEvent):
    """Emitted after each ralph loop iteration."""

    type: Literal["workflow_iteration"] = "workflow_iteration"
    iteration: int
    branch: str
    commit_sha: str | None = None
    accepted: bool
    evaluation: AcceptanceCriteriaOutput


class WorkflowCompleteEvent(AgentEvent):
    """Emitted when the ralph loop finishes."""

    type: Literal["workflow_complete"] = "workflow_complete"
    feature_branch: str
    ralph_branch: str
    total_iterations: int
    accepted: bool
    merged: bool = False
    final_commit_sha: str | None = None
    error: str | None = None
    pr_url: str | None = None
    pr_number: int | None = None
    ci_passed: bool | None = None

    @model_serializer(mode="wrap")
    def _force_ci_field(
        self,
        handler: SerializerFunctionWrapHandler,
    ) -> dict[str, object]:
        result: dict[str, object] = handler(self)
        # ci_passed is a three-state field (True/False/None) — must always appear
        key = "ciPassed" if "featureBranch" in result else "ci_passed"
        if key not in result:
            result[key] = None
        return result


class WorkflowCriteriaEvent(AgentEvent):
    """Emitted after acceptance criteria are generated from ticket analysis."""

    type: Literal["workflow_criteria"] = "workflow_criteria"
    criteria: list[str]
    reasoning: str


class WorkflowTicketDraftEvent(AgentEvent):
    """Emitted after each ticket draft iteration."""

    type: Literal["workflow_ticket_draft"] = "workflow_ticket_draft"
    iteration: int
    draft: TicketDraftOutput


class WorkflowTicketReviewEvent(AgentEvent):
    """Emitted after each ticket review iteration."""

    type: Literal["workflow_ticket_review"] = "workflow_ticket_review"
    iteration: int
    approved: bool
    feedback: str
    suggestions: list[str]


class WorkflowTicketEvent(AgentEvent):
    """Emitted when ticket generation finishes."""

    type: Literal["workflow_ticket"] = "workflow_ticket"
    ticket: TicketDraftOutput
    review_rounds: int
    approved: bool


# Pre-computed JSON schemas for structured agent output via output_format
COMMIT_MESSAGE_SCHEMA: dict[str, object] = CommitMessageOutput.model_json_schema()
# Schema for acceptance criteria evaluation results
ACCEPTANCE_CRITERIA_SCHEMA: dict[str, object] = (
    AcceptanceCriteriaOutput.model_json_schema()
)
# Schema for agent-generated branch name slugs
BRANCH_NAME_SCHEMA: dict[str, object] = BranchNameOutput.model_json_schema()
# Schema for agent-generated acceptance criteria from ticket analysis
GENERATED_CRITERIA_SCHEMA: dict[str, object] = (
    GeneratedCriteriaOutput.model_json_schema()
)
# Schema for structured ticket draft output
TICKET_DRAFT_SCHEMA: dict[str, object] = TicketDraftOutput.model_json_schema()
# Schema for structured ticket review output
TICKET_REVIEW_SCHEMA: dict[str, object] = TicketReviewOutput.model_json_schema()
PR_DESCRIPTION_SCHEMA: dict[str, object] = PRDescriptionOutput.model_json_schema()
